### ISSUE TITLE
Captcha for showing email address is outdated

### ISSUE THREAD

**Issue by anzetal** [GiantCowFilms/Blend-Exchange#42]
There are captchas to show email address. 
example: http://giantcowfilms.com/contact/
https://blend-exchange.giantcowfilms.com/help/

V1 captchas have been outdated and clicking on it shows this message:

![image](https://user-images.githubusercontent.com/35098870/39863826-615fdf48-5465-11e8-84fb-480f138b477d.png)

**Comment by GiantCowFilms** [comment]
Ah, thank you for notifying me about this.

**Comment by jackflyer** [comment]
Hi, Captcha is not working.
