### ISSUE TITLE
Unable to upload blends

### ISSUE THREAD

**Issue by sambler** [GiantCowFilms/Blend-Exchange#43]
I have used blend-exchange several times before but the last two days I have had an issue uploading. You may be able to find several copies of the same file that can be deleted from my attempts.

When the upload completes I see an accept the terms error and don't get the link to use.

I am using firefox 60.0.2 on FreeBSD

![screenshot](https://i.stack.imgur.com/1A1KO.jpg)

**Comment by GiantCowFilms** [comment]
I believe this issue is caused when the url contains a # sign. I am currently re-writing the site, and will ensure this issue is rectified in the new version.

**Comment by GiantCowFilms** [comment]
Closing this issue. The upgrade should have fixed this some time ago.

**Comment by ghost** [comment]
It has not. I am having the same issue, and I don't have a _#_ sign in my URL. In fact, I'm not uploading with a URL.

**Comment by GiantCowFilms** [comment]
@ConnorAhern You need to provide a question URL (if you are using the extension like in the post the URL will appear as a parameter in the URL shown in the browser.

**Comment by ghost** [comment]
> @ConnorAhern You need to provide a question URL (if you are using the extension like in the post the URL will appear as a parameter in the URL shown in the browser.

https://blender.stackexchange.com/questions/242144/huge-chunks-of-the-video-are-misarranged-or-missing-in-the-render-but-theyre-f

**Comment by GiantCowFilms** [comment]
Closing this issue as it was raised for the 1.0 version of the site.
