### ISSUE TITLE
Email link on the Help page not working

### ISSUE THREAD

**Issue by baldingwizard** [GiantCowFilms/Blend-Exchange#45]
The email address on the Help page shows as 'b...@giantcowfilms.com with a tooltip to 'Reveal this email address'. However, clicking it simply opens a window with a 'Not Found', 'Error 404' page.

**Comment by GiantCowFilms** [comment]
Google got rid of re-captcha's mailhide feature, I need to update it with a contact form or something. Wont be able to fix soon though, unfortunately.
