### ISSUE TITLE
File statistics not working

### ISSUE THREAD

**Issue by baldingwizard** [GiantCowFilms/Blend-Exchange#46]
The statistics shown for an uploaded file do not appear to be working correctly. By simply pressing Refresh on the web browser refreshes the page and seems to show different statistics for the same file. For example, opening https://blend-exchange.giantcowfilms.com/b/5155/ initially shows statistics as '3 views, 2 downloads, 1 favorites' but clicking 'Refresh' resulted in '6 views, 0 downloads, 1 favorites'. Clicking refresh again resulted in '5 views, 3 downloads, 0 favorites'.... it seems to change each time the page is refreshed.

**Comment by GiantCowFilms** [comment]
This is by design, the values are randomized slightly, roughly +/- 5. This is done to prevent methods of determining user IP addresses. I'm working on a better solution for the new version, this was just a hasty patch.
