### ISSUE TITLE
3.1 blend files are not recognised as blend file

### ISSUE THREAD

**Issue by mond-cz** [GiantCowFilms/Blend-Exchange#56]
I have **some** .blend files (currently 3.1) that are not recognised as a blend file. 
I tried to upload file with default setup + Geometry nodes only enabled ... and it works, but other files with some examples to answer can't be uploaded.

Any known issue with that?
Thank you for help.

**Comment by GiantCowFilms** [comment]
Can you provide me with a sample file that you cannot upload so I can debug this?

**Comment by mond-cz** [comment]
Like this one from 3.1 ... 
[test_Clay310.blend.zip](https://github.com/GiantCowFilms/Blend-Exchange/files/7762118/test_Clay310.blend.zip)
(The same file, but saved under 2.93 works fine.)

iMac, Safari, Chrome, ... Thank you

**Comment by mond-cz** [comment]
... another one ...
[test_Nishita_480px.blend.zip](https://github.com/GiantCowFilms/Blend-Exchange/files/7801377/test_Nishita_480px.blend.zip)

**Comment by mond-cz** [comment]
... another one ... btw same happened with this file at pasteall.org site.
[test_Chocolate_SSS_opti.blend.zip](https://github.com/GiantCowFilms/Blend-Exchange/files/7887301/test_Chocolate_SSS_opti.blend.zip)

**Comment by GiantCowFilms** [comment]
Thanks for providing the examples, I will take a look at this as soon as I have some free time. I apologize for the delay, I've been incredibly busy.

**Comment by GiantCowFilms** [comment]
The issue is the compression format was changed in blender 3.0 (https://blender.meta.stackexchange.com/questions/2857/blend-exchange-not-accepting-v3-x-files/2858?noredirect=1#comment6495_2868)

**Comment by mond-cz** [comment]
Thanks for info :) Great to know ... I was surpised nobody complaine to this issue ... now I know why - nobody compressed blends :)

**Comment by mond-cz** [comment]
Compression is not the only one reason ... I tried several 3.1 without compression now, with this error ... https://imgur.com/2CfdBdh

**Comment by stillpointx** [comment]
> Compression is not the only one reason ... I tried several 3.1 without compression now, with this error ... https://imgur.com/2CfdBdh

I'm having the same issue no compression

**Comment by GiantCowFilms** [comment]
@stillpointx One of our storage providers changed how their API operates, upload is completely broken until I can fix this (Hopefully within the next few hours).

**Comment by stillpointx** [comment]
> @stillpointx One of our storage providers changed how their API operates, upload is completely broken until I can fix this (Hopefully within the next few hours).

@GiantCowFilms 
Thanks! for the update and your hard work..  I know this stuff can be very frustrating at times especially when someone else caused the issue.  That's the reason I got out of Dev and Sysadmin stuff, people kept breaking stuff and I had to fix it hahahah .. ;-)

**Comment by GiantCowFilms** [comment]
I have disabled validation for blend files until I can find the time to right new validation that supports the new compression format used by blender 3.0 and above.
