### ISSUE TITLE
There was an Internal error attempting to complete your request

### ISSUE THREAD

**Issue by stillpointx** [GiantCowFilms/Blend-Exchange#59]
There was an Internal error attempting to complete your request

It's a blend file created in 3.1.0 beta not using compression.  Here's the file to test with.

[indent tube and spiral equation combo gn.blend.zip](https://github.com/GiantCowFilms/Blend-Exchange/files/8147931/indent.tube.and.spiral.equation.combo.gn.blend.zip)

![screenshot-February-26-2022-22-10-18](https://user-images.githubusercontent.com/28985314/155866731-de470f88-6155-4a7f-a404-4c6357253f11.png)

**Comment by GiantCowFilms** [comment]
Duplicate of #57
