### ISSUE TITLE
Size Limitation Display

### ISSUE THREAD

**Issue by samuelsullins** [GiantCowFilms/Blend-Exchange#60]
The site cannot accept .blend files beyond a certain size, but it only tells you after you upload one.

Would it make sense to display the size limit on the page so that the user could prepare for it ahead of time?

**Comment by GiantCowFilms** [comment]
Yeah, this would be a good addition, I'll see if I can add it at some point.

**Comment by GiantCowFilms** [comment]
Added in https://github.com/GiantCowFilms/Blend-Exchange/commit/d42d6bc5f0633e2b7f144ed1812d10eaada2eab8
