### ISSUE TITLE
I can't upload my blender file (.blend) "files must be in blend format"

### ISSUE THREAD

**Issue by alexisriverab3d** [GiantCowFilms/Blend-Exchange#61]
I am trying to upload my blend file but I get this message that says "All uploaded files must be in the blend file format". I am using Blender version 3.2

![Blend File Error](https://user-images.githubusercontent.com/108655284/177105161-a165bda3-25d1-4a88-ac57-b7f1d90d0864.png)

**Comment by Zophiekat** [comment]
I'm having this same issue with Blender 3.2.2

**Comment by GiantCowFilms** [comment]
@Zophiekat Can you provide the file that you were unable to upload? I disabled the validation checks, so it should no longer be possible to get this error message.

**Comment by Zophiekat** [comment]
@GiantCowFilms hi, sure here it is https://drive.google.com/file/d/1WaBBBELUtN8oMC9Bfa9p4QEagE83mt9r/view?usp=drivesdk

**Comment by GiantCowFilms** [comment]
Issue has been corrected fully. Sorry for the delay.
