### ISSUE TITLE
Error "There was an internal error attempting to complete your request"

### ISSUE THREAD

**Issue by Lauloque** [GiantCowFilms/Blend-Exchange#63]
I was warned by [a user trying to upload][1] that it was giving an error:  
`There was an internal error attempting to complete your request.`

And it does the same for me for any file, even a default scene.

[![enter image description here][2]][2]

I also tried with different topic links.

I posted on BSE Meta: [Blend-Exchange unable to upload files - Blender Meta Stack Exchange](https://blender.meta.stackexchange.com/questions/3101/blend-exchange-unable-to-upload-files)

But I also post here to make sure it gets noticed on both concerned channels.

  [1]: https://blender.stackexchange.com/questions/327955/exporting-both-blend-and-fbx-file-from-blender-to-unity-creates-unexpected-res?noredirect=1#comment573327_327955
  [2]: https://i.sstatic.net/65OgX6sB.png

**Comment by GiantCowFilms** [comment]
Hi! I am aware of the issue and will work on a fix as soon as I have a chance. Thank you for notifying me.

**Comment by GiantCowFilms** [comment]
Issue should be resolved, please try uploading again

**Comment by Lauloque** [comment]
Woah, that was fast! Thank you :)
